# Generated by Django 4.2.7 on 2026-01-16 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('code_client', models.CharField(max_length=20, unique=True, verbose_name='Code client')),
                ('contact_nom', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('contact_telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('type_abonnement', models.CharField(choices=[('prepaye', 'Prépayé'), ('postpaye', 'Postpayé'), ('credit', 'Crédit')], max_length=20, verbose_name="Type d'abonnement")),
                ('solde_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde USD')),
                ('solde_fc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde FC')),
                ('limite_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Limite de crédit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Abonné actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Abonné',
                'verbose_name_plural': 'Abonnés',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du moyen de paiement')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Moyen actif')),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Pompiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pompistes/photos/', verbose_name='Photo')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse de résidence')),
                ('quart', models.CharField(choices=[('jour', 'Jour'), ('nuit', 'Nuit')], default='jour', max_length=10, verbose_name='Quart de travail')),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire')),
                ('devise_salaire', models.CharField(choices=[('USD', 'Dollar Américain'), ('FC', 'Franc Congolais')], default='USD', max_length=3, verbose_name='Devise du salaire')),
                ('contrat', models.FileField(blank=True, null=True, upload_to='pompistes/contrats/', verbose_name='Contrat de travail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Pompiste actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branche', verbose_name='Branche')),
            ],
            options={
                'verbose_name': 'Pompiste',
                'verbose_name_plural': 'Pompistes',
                'ordering': ['branche', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantité (L)')),
                ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant USD')),
                ('montant_fc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant FC')),
                ('taux_change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taux de change appliqué')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('manquant', 'Manquant signalé'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('manquant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Manquant USD')),
                ('manquant_fc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Manquant FC')),
                ('raison_manquant', models.TextField(blank=True, verbose_name='Raison du manquant')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('abonne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.abonne', verbose_name='Abonné')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branche', verbose_name='Branche')),
                ('caissier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('moyen_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moyenpaiement', verbose_name='Moyen de paiement')),
                ('pompiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pompiste', verbose_name='Pompiste')),
                ('type_carburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typecarburant', verbose_name='Type de carburant')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], max_length=3, verbose_name='Devise')),
                ('periode', models.CharField(max_length=50, verbose_name='Période (ex: Janvier 2024)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Payé le')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branche', verbose_name='Branche')),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('employe_pompiste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pompiste', verbose_name='Pompiste')),
                ('employe_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employé utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement de salaire',
                'verbose_name_plural': 'Paiements de salaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité livrée (L)')),
                ('fournisseur', models.CharField(max_length=100, verbose_name='Fournisseur')),
                ('reference_document', models.CharField(blank=True, max_length=50, verbose_name='Référence document')),
                ('date_livraison', models.DateTimeField(verbose_name='Date de livraison')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livree', 'Livrée'), ('confirmee', 'Confirmée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branche', verbose_name='Branche')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('type_carburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typecarburant', verbose_name='Type de carburant')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_livraison'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], max_length=3, verbose_name='Devise')),
                ('methode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank', 'Virement Bancaire')], max_length=20, verbose_name='Méthode de paiement')),
                ('beneficiaire', models.CharField(blank=True, max_length=100, verbose_name='Bénéficiaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='approuvee', max_length=20, verbose_name='Statut')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/', verbose_name='Justificatif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branche', verbose_name='Branche')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriedepense', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsommationAbonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonne', verbose_name='Abonné')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branche', verbose_name='Branche')),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.vente', verbose_name='Vente associée')),
            ],
            options={
                'verbose_name': 'Consommation abonné',
                'verbose_name_plural': 'Consommations abonnés',
                'ordering': ['-vente__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité actuelle (L)')),
                ('capacite_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacité maximale (L)')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Seuil d'alerte (L)")),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Prix d'achat (USD/L)")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branche', verbose_name='Branche')),
                ('type_carburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typecarburant', verbose_name='Type de carburant')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['branche', 'type_carburant'],
                'unique_together': {('branche', 'type_carburant')},
            },
        ),
    ]
